package com.sample.facts;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Airplane implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "AIRPLANE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "AIRPLANE_ID_GENERATOR", sequenceName = "AIRPLANE_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("着陸料")
   private int landingFee;

   @org.kie.api.definition.type.Label("停留料")
   private int stayingFee;

   @org.kie.api.definition.type.Label("軽減率")
   private double discountRate;

   @org.kie.api.definition.type.Label("最大着陸重量")
   private int maxTakeoffWeight;

   @org.kie.api.definition.type.Label("タイプ")
   private java.lang.String airplaneType;

   @org.kie.api.definition.type.Label("騒音値離陸")
   private double takeoffNoise;

   @org.kie.api.definition.type.Label("騒音値進入")
   private double enteringNoise;

   @org.kie.api.definition.type.Label("停留時間")
   private int stayingTime;

   @org.kie.api.definition.type.Label("離陸空港")
   private java.lang.String takeoffAirport;

   @org.kie.api.definition.type.Label("新規就航増便")
   private Boolean newFlightLine;

   @org.kie.api.definition.type.Label("空港会社新規路線")
   private Boolean airlineNewFlight;

   @org.kie.api.definition.type.Label("成田空港新規路線")
   private Boolean naritaNewFlight;

   @org.kie.api.definition.type.Label("新規路線年度")
   private int newFlightYear;

   @org.kie.api.definition.type.Label("前年度累積着陸料")
   private int prevYearAccumulateLandingFee;

   @org.kie.api.definition.type.Label("今年度累積着陸料")
   private int thisYearAccumulateLandingFee;

   @org.kie.api.definition.type.Label("インセンティブ割引料")
   private int insentiveDiscountRate;

   @org.kie.api.definition.type.Label("インセンティブ割引料")
   private int insentiveDiscountFee;

   @org.kie.api.definition.type.Label("最終着陸料")
   private int finalLandingFee;

   @org.kie.api.definition.type.Label("運行計画到着時刻")
   private java.util.Date plannedArrivalTime;

   @org.kie.api.definition.type.Label("直前離陸島")
   private java.lang.String takeoffIsland;

}